### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by COLABORATI** [allo-/feedjack#15]
```
error in Feedjack setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'< 1.10'"
```

**Comment by allo-** [comment]
Do you use recent pip and python 2?
Try a virtualenv first:

```
virtualenv feedjack-venv
cd feedjack-venv
source bin/activate
pip -U pip
pip -e /path/to/checkout
```

If it still does not work, maybe it's broken. I currently use it from a checkout without installation and do a lot of refactoring.

**Comment by COLABORATI** [comment]
I have the latest version of pip in a python 2.7.12 virtualenv. My pip, btw, does not know a `-U` option. 
yes, so maybe it is broken :)

**Comment by allo-** [comment]
meh, `pip install -U pip` of course.
And there is a comma missing.

**Comment by COLABORATI** [comment]
Yes! I just again tried to read the [doc](https://docs.python.org/2/distutils/setupscript.html) but your commit was faster, thanks! Works.

**Comment by allo-** [comment]
Yeah, just read an example from another project for the right syntax. Often that's the fastest ;-).
